### ISSUE TITLE
Rationale for setting date_max in pub_data_visualization/production/load/load.py

### ISSUE THREAD

**Issue by pgrt** [cre-dev/pub-data-visualization#3]
Hello,

I saw you are currently imposing hardcoded default bounds date_min and date_max in the aforementioned file. I understand well the reason for putting 2012 in date_min, but is there one for setting 2019 in date_max?

I tried to launch pub_scripts/multiplots/main_transparent_production.py with no defined dates and with data files from 2015 up to 2020 and the production silently failed to be included in the graph, whereas the capacity was plotted.

If there is a reason for setting this upper limit, is it possible to print a warning when posterior data are discarded from dg in the function, and could you document the reason?
Else, could you consider removing this limit?

In any case, thanks for your code which is extremely reliable and helpful.

Best,
Pierre Gruet

**Comment by cre-os** [comment]
Hello,

The original reason is the following : 
If you choose eCO2mix but do not have the data on your computer, the program will fetch the data online. To make sure that
`urllib.request.urlretrieve` does not produce an error i.e. the url is a valid one, I had set those limits.

This may not be a very good reason. I will change 2019 with sth like 2030 and add something to deal with errors encountered by `urllib.request.urlretrieve` so that the hard-coded limits can be safely removed in the end.

**Comment by pgrt** [comment]
Hello,

Thanks for the explanation, I understand well. For my own use, I did something quite similar to what you are suggesting by setting a distant date.

I guess this could also be done on your published code if you think it is safe.

Thanks again,
Pierre

**Comment by cre-os** [comment]
The default value for date_min has been set to 2012 directly in the submodule to load eco2mix data, while the the default value for date_max has been set to datetime.datetime.now().
